### ISSUE TITLE
Getting: uninitialized constant Gelauto::VERSION (NameError)

### ISSUE THREAD

**Issue by jasnow** [camertron/gelauto#1]
When I run "gelauto run --annotate $(find . -name '*.rb') -- bundle rspec spec",
I get this:
```
Traceback (most recent call last):
	4: from /Users/USER/.rvm/gems/ruby-2.6.3@ruby2.6-rails5.2/bin/gelauto:23:in `<main>'
	3: from /Users/USER/.rvm/gems/ruby-2.6.3@ruby2.6-rails5.2/bin/gelauto:23:in `load'
	2: from /Users/USER/.rvm/gems/ruby-2.6.3@ruby2.6-rails5.2/gems/gelauto-1.0.0/bin/gelauto:6:in `<top (required)>'
	1: from /Users/USER/.rvm/gems/ruby-2.6.3@ruby2.6-rails5.2/gems/gelauto-1.0.0/bin/gelauto:7:in `<module:Gelauto>'
/Users/USER/.rvm/gems/ruby-2.6.3@ruby2.6-rails5.2/gems/gelauto-1.0.0/bin/gelauto:12:in `<module:CLI>': uninitialized constant Gelauto::VERSION (NameError)
```
Previously I ran "gem install gelauto".

Running on a Mac OS 10.12.6 on Mid 2014 MacBook Pro.

**Comment by jasnow** [comment]
Also get it when I run "gelauto" by itself.

**Comment by jasnow** [comment]
@camertron - Is this a real issue?

**Comment by camertron** [comment]
@jasnow argh sorry about that. Not sure why I didn't catch this earlier. All that's needed is to `require 'gelauto/version'` in bin/gelauto so the `VERSION` constant is available. Just published v1.0.1 of the gem. Let me know if that fixes things :)

**Comment by jasnow** [comment]
Suggest creating a channel on Sorbet for your tool. Verified fix so closing this issue.

**Comment by camertron** [comment]
@jasnow ok sure. Slack? IRC?

**Comment by jasnow** [comment]
Sent you an invite to Sorbet Slack.

**Comment by camertron** [comment]
👍
