### ISSUE TITLE
Splat operator (`*`) without argument breaks annotation

### ISSUE THREAD

**Issue by Willianvdv** [camertron/gelauto#12]
Here's the generated code:
```
sig { params(: T.untyped).void }
def initialize(*)
   super
end
```

**Comment by camertron** [comment]
Oops, thanks @Willianvdv. What should it emit in this case? There's technically no arg name, so what should the signature look like?

**Comment by Willianvdv** [comment]
Hey @camertron, I'm not sure and tbh I can't remember what thing I was working on when I stumbled upon this issue 😂
