### ISSUE TITLE
Detect whether method has signature and skip gelauto on it

### ISSUE THREAD

**Issue by hdoan741** [camertron/gelauto#13]
> Gelauto ignores existing type signatures and will simply add another one right above the method.

I think this is a big usability issue because it's difficult to use gelauto on a file that already has some methods with signatures. It is possible to detect whether there is a sorbet signature around a method or not and skip sig generation for the method

See example: https://github.com/chanzuckerberg/sorbet-rails/blob/master/lib/sorbet-rails/sorbet_utils.rb#L11

**Comment by camertron** [comment]
Agreed, thanks @manhhung741. I'll see if I can get to this in the next few weeks.

**Comment by camertron** [comment]
This functionality was kindly contributed by @wpride and has been released in v2.1.0 ❤️
