### ISSUE TITLE
Add support for "test" directory

### ISSUE THREAD

**Issue by jasnow** [camertron/gelauto#2]
Add support for "test" directory.

Example:
```
gelauto run --annotate $(find . -name '*.rb') -- bundle exec rake
```

**Comment by jasnow** [comment]
This appears to work:
```
gelauto run --rbi $(find . -name *.rb) -- bundle exec rake test/
```

**Comment by camertron** [comment]
Yeah I've noticed you have to pass directory arguments like this for `rspec` too, i.e. `bundle exec rspec spec/` whereas normally just `bundle exec rspec` would work. It probably has something to do with the fact that both Gelauto, RSpec, and Rake all make use of `ARGV`, but that's just a hunch.

**Comment by jasnow** [comment]
I think this issue can be closed after the README PR is merged.

**Comment by jasnow** [comment]
Covered by other issues and PR's.
