### ISSUE TITLE
--rbi missing from "--help" output and unknown option

### ISSUE THREAD

**Issue by jasnow** [camertron/gelauto#4]
```
just released v1.1.0 that logs to STDERR instead of STDOUT. Also added a global --silent flag and --rbi option for the run subcommand.
```
Do not see the **--rbi** in "--help" output.

When I tried "--rbi", I get: error: Unknown option --rbi

**Comment by camertron** [comment]
@jasnow I believe `--rbi` is a command-specific flag, so you have to put it _after_ `run`, eg:

```bash
gelauto --silent run --rbi <rest of args>
```

The `--rbi` option shows up in the help for the `run` subcommand, which you can see by running `gelauto help run`

**Comment by jasnow** [comment]
Know I understand.
